# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HyperdeckRecUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(690, 500, 89, 25))
        self.quitButton.setObjectName("quitButton")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(690, 100, 89, 25))
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(690, 150, 89, 25))
        self.stopButton.setObjectName("stopButton")
        self.DateTimeDisp = QtWidgets.QLabel(self.centralwidget)
        self.DateTimeDisp.setGeometry(QtCore.QRect(60, 30, 300, 30))
        self.DateTimeDisp.setFrameShape(QtWidgets.QFrame.Box)
        self.DateTimeDisp.setObjectName("DateTimeDisp")
        self.JDSflash = QtWidgets.QLabel(self.centralwidget)
        self.JDSflash.setGeometry(QtCore.QRect(450, 30, 30, 30))
        self.JDSflash.setFrameShape(QtWidgets.QFrame.Box)
        self.JDSflash.setScaledContents(True)
        self.JDSflash.setAlignment(QtCore.Qt.AlignCenter)
        self.JDSflash.setObjectName("JDSflash")
        self.ODRflash = QtWidgets.QLabel(self.centralwidget)
        self.ODRflash.setGeometry(QtCore.QRect(510, 30, 30, 30))
        self.ODRflash.setFrameShape(QtWidgets.QFrame.Box)
        self.ODRflash.setScaledContents(False)
        self.ODRflash.setAlignment(QtCore.Qt.AlignCenter)
        self.ODRflash.setObjectName("ODRflash")
        self.clipGB = QtWidgets.QGroupBox(self.centralwidget)
        self.clipGB.setGeometry(QtCore.QRect(60, 80, 590, 140))
        self.clipGB.setObjectName("clipGB")
        self.clipGB_label = QtWidgets.QLabel(self.clipGB)
        self.clipGB_label.setGeometry(QtCore.QRect(10, 30, 570, 100))
        self.clipGB_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clipGB_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.clipGB_label.setObjectName("clipGB_label")
        self.clipGB_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.clipGB_2.setGeometry(QtCore.QRect(60, 235, 590, 140))
        self.clipGB_2.setObjectName("clipGB_2")
        self.clipGB_2_label = QtWidgets.QLabel(self.clipGB_2)
        self.clipGB_2_label.setGeometry(QtCore.QRect(10, 30, 570, 100))
        self.clipGB_2_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clipGB_2_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.clipGB_2_label.setObjectName("clipGB_2_label")
        self.clipGB_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.clipGB_3.setGeometry(QtCore.QRect(60, 390, 590, 140))
        self.clipGB_3.setObjectName("clipGB_3")
        self.clipGB_3_label = QtWidgets.QLabel(self.clipGB_3)
        self.clipGB_3_label.setGeometry(QtCore.QRect(10, 30, 570, 100))
        self.clipGB_3_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clipGB_3_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.clipGB_3_label.setObjectName("clipGB_3_label")
        self.idleIcon = QtWidgets.QGroupBox(self.centralwidget)
        self.idleIcon.setGeometry(QtCore.QRect(690, 30, 40, 40))
        self.idleIcon.setObjectName("idleIcon")
        self.recIconLabel = QtWidgets.QLabel(self.idleIcon)
        self.recIconLabel.setGeometry(QtCore.QRect(5, 20, 30, 15))
        self.recIconLabel.setText("")
        self.recIconLabel.setObjectName("recIconLabel")
        self.clipTimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.clipTimeLabel.setGeometry(QtCore.QRect(690, 290, 89, 30))
        self.clipTimeLabel.setObjectName("clipTimeLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HyperdeckRecorderUI"))
        self.quitButton.setText(_translate("MainWindow", "Quit"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.DateTimeDisp.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">DateTimeDisp</span></p></body></html>"))
        self.JDSflash.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">J</span></p></body></html>"))
        self.ODRflash.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">O</span></p></body></html>"))
        self.clipGB.setTitle(_translate("MainWindow", "clipGB"))
        self.clipGB_label.setText(_translate("MainWindow", "clipDisplay"))
        self.clipGB_2.setTitle(_translate("MainWindow", "clipGB_2"))
        self.clipGB_2_label.setText(_translate("MainWindow", "clipDisplay"))
        self.clipGB_3.setTitle(_translate("MainWindow", "clipGB_3"))
        self.clipGB_3_label.setText(_translate("MainWindow", "clipDisplay"))
        self.idleIcon.setTitle(_translate("MainWindow", "Rec"))
        self.clipTimeLabel.setText(_translate("MainWindow", "clipTime"))
